name: Building & Publishing Package to PyPI
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
      with:
        cache: 'pip'
        cache-dependency-path: '.github/workflows/requirements/publish.txt'

    - name: Install Python dependencies
      run: |
        pip install -r .github/workflows/requirements/publish.txt

    - name: Build package
      run: |
        python3 -m build

    - name: Save distribution files as artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: python-package-distributions
        path: dist/

  push:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/repligit
    permissions:
      id-token: write
    steps:
    - name: Download distribution files from artifact
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
