name: save base branch coverage

on:
  push:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: 'refs/heads/main'

      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: |
            '.github/workflows/requirements/unit-tests.txt'

      - name: Install Python dependencies
        run: |
          pip install .
          pip install -r .github/workflows/requirements/unit-tests.txt

      - name: Generate coverage
        run: |
          coverage run -m pytest
          coverage json -o coverage.json

      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: base-coverage
          path: coverage.json
