name: Linting & Style Checks
on:
  # This Workflow can be triggered manually
  workflow_dispatch:
  workflow_call:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Python 3.10
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '.github/workflows/requirements/style.txt'

      - name: Install Python dependencies
        run: |
          pip install -r .github/workflows/requirements/style.txt

      - name: Run Ruff
        run: |
          ruff check --diff
          ruff check --select I --diff
          ruff format --check --diff

      - name: Run Typos
        run: typos
