name: Unit Tests
on:
  # This Workflow can be triggered manually
  workflow_dispatch:
  workflow_call:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.13']
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            'pyproject.toml'
            '.github/workflows/requirements/unit-tests.txt'

      - name: Install Python dependencies
        run: |
          pip install .
          pip install -r .github/workflows/requirements/unit-tests.txt

      - name: Run Unit Tests with Pytest
        run: |
          python3 -m build  # build package for compatibility with publish.yml
          python3 -m pytest
